package com.example.demo2.dao;

import com.example.demo2.beans.Answer;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface AnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    int deleteByPrimaryKey(Integer answerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    int insert(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    Answer selectByPrimaryKey(Integer answerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    List<Answer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    int updateByPrimaryKey(Answer record);
    List<Answer> selectByUsername(String username);
    List<Answer> selectByQuestionId(int questionId);
}