package com.example.demo2.dao;

import com.example.demo2.beans.Message;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    int deleteByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    Message selectByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    List<Message> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    int updateByPrimaryKey(Message record);
    List<Message> getAllMessageByQuestionId(int questionId);
    List<Message> getAllMessageByMessageManR(String messageManR);
}