package com.example.demo2.dao;

import com.example.demo2.beans.User;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ques_answ
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ques_answ
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ques_answ
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    User selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ques_answ
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ques_answ
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    int updateByPrimaryKey(User record);
    //用户登录时的查询
    User selectByUsernameAndPassword(String username,String password);

}