package com.example.demo2.beans;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Answer {


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.answer_id
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */

    private Integer answerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.publish_time
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.question_vector
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    private String questionVector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.question
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    private Integer question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.answer_content
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    private String answerContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.answer_id
     *
     * @return the value of answer.answer_id
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public Integer getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.answer_id
     *
     * @param answerId the value for answer.answer_id
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.publish_time
     *
     * @return the value of answer.publish_time
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.publish_time
     *
     * @param publishTime the value for answer.publish_time
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.question_vector
     *
     * @return the value of answer.question_vector
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public String getQuestionVector() {
        return questionVector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.question_vector
     *
     * @param questionVector the value for answer.question_vector
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public void setQuestionVector(String questionVector) {
        this.questionVector = questionVector == null ? null : questionVector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.question
     *
     * @return the value of answer.question
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public Integer getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.question
     *
     * @param question the value for answer.question
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public void setQuestion(Integer question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.answer_content
     *
     * @return the value of answer.answer_content
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public String getAnswerContent() {
        return answerContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.answer_content
     *
     * @param answerContent the value for answer.answer_content
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public void setAnswerContent(String answerContent) {
        this.answerContent = answerContent == null ? null : answerContent.trim();
    }
}