package com.example.demo2.beans;

import java.util.Date;

public class Message {


    public Date getPublishTime() {
        return publishTime;
    }

    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_id
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    private Date publishTime;

    public Integer getAnswerId() {
        return answerId;
    }

    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }

    private Integer answerId;
    private Integer messageId;

    public String getMessageManR() {
        return messageManR;
    }

    public void setMessageManR(String messageManR) {
        this.messageManR = messageManR;
    }
    private String messageManR;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_man
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    private String messageMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.question
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    private Integer question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_content
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    private String messageContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_id
     *
     * @return the value of message.message_id
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_id
     *
     * @param messageId the value for message.message_id
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_man
     *
     * @return the value of message.message_man
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public String getMessageMan() {
        return messageMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_man
     *
     * @param messageMan the value for message.message_man
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public void setMessageMan(String messageMan) {
        this.messageMan = messageMan == null ? null : messageMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.question
     *
     * @return the value of message.question
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public Integer getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.question
     *
     * @param question the value for message.question
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public void setQuestion(Integer question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_content
     *
     * @return the value of message.message_content
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_content
     *
     * @param messageContent the value for message.message_content
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent == null ? null : messageContent.trim();
    }
}