package com.example.demo2.beans;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Date;

public class User {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ques_answ.username
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */

    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ques_answ.password
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    @JsonIgnore
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ques_answ.picture
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */

    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ques_answ.regtime
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    private Date regtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ques_answ.username
     *
     * @return the value of user_ques_answ.username
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ques_answ.username
     *
     * @param username the value for user_ques_answ.username
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ques_answ.password
     *
     * @return the value of user_ques_answ.password
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ques_answ.password
     *
     * @param password the value for user_ques_answ.password
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ques_answ.picture
     *
     * @return the value of user_ques_answ.picture
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ques_answ.picture
     *
     * @param picture the value for user_ques_answ.picture
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ques_answ.regtime
     *
     * @return the value of user_ques_answ.regtime
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ques_answ.regtime
     *
     * @param regtime the value for user_ques_answ.regtime
     *
     * @mbg.generated Wed Jun 19 22:49:44 CST 2019
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
}